model: 'sbd'
network: 'ro_34'
task: 'snake'
resume: true
gpus: (0, 1, 2, 3)

train:
    optim: 'adam'
    lr: 1e-4
    milestones: (80, 120, 150, 170)
    gamma: 0.5
    batch_size: 80
    dataset: 'SbdTrain'
    num_workers: 32
    epoch: 200
test:
    dataset: 'SbdMini'
    batch_size: 1
    epoch: 159
